---
kind: Service
apiVersion: v1
metadata:
  name: spring-web-test-service
spec:
  selector:
    app: spring-web-test
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8081
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-web-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-web-test
  template:
    metadata:
      labels:
        app: spring-web-test
    spec:
      containers:
        - name: spring-web-test
          image: mithilesh749/spring-web-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080